### ISSUE TITLE
20190219 CM 

### ISSUE THREAD

**Issue by BIGDATA-LOGIN** [BIGDATA-LOGIN/D-Law#3]

**Comment by BIGDATA-LOGIN** [comment]
These are fixed, please check.

**Comment by puiyu** [comment]
didn't fix
[20190219_CM.xlsx](https://github.com/BIGDATA-LOGIN/D-Law/files/2899456/20190219_CM.xlsx)
